# Generated by Django 5.2.6 on 2025-10-02 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoardGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('players_min', models.IntegerField()),
                ('players_max', models.IntegerField()),
                ('status', models.CharField(choices=[('available', 'Available'), ('borrowed', 'Borrowed')], default='available', max_length=20)),
            ],
        ),
    ]
